name: Test run

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test.yml"

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run application
        run: npm run start
        env:
          DRY_RUN: True
          OSMCHA_TOKEN: ${{ secrets.OSMCHA_TOKEN }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: mapcomplete-stats.log
      - name: Upload example output
        uses: actions/upload-artifact@v4
        with:
          name: example-output
          path: mqttData.json
